%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Mohammad Khaled\Desktop\AIrfoilData.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 16-May-2022 13:23:22

%% Set up the Import Options and import the data
function[x,y]=Import_Script_airfoil(path)
opts = spreadsheetImportOptions("NumVariables", 2);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A1:B131";

% Specify column names and types
opts.VariableNames = ["X","U"];
opts.VariableTypes = ["double", "double"];

% Import the data
tbl = readtable(path, opts, "UseExcel", false);

%% Convert to output type
x_T = tbl.X;
y_T = tbl.U;
x=x_T;
y=y_T;
%% Clear temporary variables
clear opts tbl
end